# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
      timezone: "Europe/London"
    open-pull-requests-limit: 500

  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
      timezone: "Europe/London"
    open-pull-requests-limit: 500

  - package-ecosystem: npm
    directory: /
    cooldown:
      default-days: 7
      semver-major-days: 30
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
      timezone: "Europe/London"
    open-pull-requests-limit: 500

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: daily
